#!/usr/bin/env node
/**
 * Developer tool: regenerate src-tauri/src/db/icd10_seed.sql from CMS ICD-10-CM data.
 *
 * Usage:
 *   node scripts/seed-icd10.mjs
 *   node scripts/seed-icd10.mjs --year 2026
 *
 * Downloads the CMS FY{year} ICD-10-CM code descriptions ZIP, parses the
 * fixed-width text file, and writes batch INSERT statements to icd10_seed.sql.
 * Run this once per fiscal year when CMS publishes new codes.
 */

import { createWriteStream, createReadStream } from 'node:fs';
import { writeFile, mkdir, rm } from 'node:fs/promises';
import { createInterface } from 'node:readline';
import { pipeline } from 'node:stream/promises';
import { createUnzip } from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const OUT_FILE = path.join(REPO_ROOT, 'src-tauri', 'src', 'db', 'icd10_seed.sql');
const TMP_DIR = path.join(REPO_ROOT, '.tmp-icd10');

const YEAR = (() => {
  const idx = process.argv.indexOf('--year');
  return idx !== -1 ? process.argv[idx + 1] : '2025';
})();

// CMS publishes ICD-10-CM at a stable URL pattern each fiscal year.
const CMS_ZIP_URL =
  `https://www.cms.gov/files/zip/${YEAR}-code-descriptions-tabular-order.zip`;

const BATCH_SIZE = 1000;

function escape(s) {
  return s.replace(/'/g, "''");
}

async function downloadZip(url, dest) {
  console.log(`Downloading ${url} ...`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  const out = createWriteStream(dest);
  await pipeline(res.body, out);
  console.log(`Saved ZIP to ${dest}`);
}

async function extractCodesFile(zipPath, outDir) {
  // Node stdlib has no zip reader; use a streaming unzip approach via child_process.
  const { execFile } = await import('node:child_process');
  const { promisify } = await import('node:util');
  const execFileAsync = promisify(execFile);

  // List zip contents to find the codes file
  let listing;
  try {
    const { stdout } = await execFileAsync('unzip', ['-l', zipPath]);
    listing = stdout;
  } catch {
    throw new Error('`unzip` not found. Install it with: brew install unzip');
  }

  const match = listing.match(/icd10cm_codes_\d{4}\.txt/i);
  if (!match) throw new Error('Could not find icd10cm_codes_*.txt in ZIP listing:\n' + listing);
  const filename = match[0];

  console.log(`Extracting ${filename} ...`);
  await execFileAsync('unzip', ['-o', zipPath, filename, '-d', outDir]);
  return path.join(outDir, filename);
}

async function parseCodes(codesFile) {
  const rl = createInterface({ input: createReadStream(codesFile), crlfDelay: Infinity });
  const codes = [];
  for await (const line of rl) {
    if (!line.trim()) continue;
    // Fixed-width: first 7 chars = code (trimmed), rest = description
    const code = line.slice(0, 7).trim();
    const description = line.slice(7).trim();
    if (code && description) codes.push({ code, description });
  }
  return codes;
}

function buildSql(codes) {
  const lines = [
    `-- ${codes.length} ICD-10-CM codes (CMS FY${YEAR}, public domain)`,
    `-- Generated by scripts/seed-icd10.mjs — do not edit manually`,
    '',
  ];

  for (let i = 0; i < codes.length; i += BATCH_SIZE) {
    const batch = codes.slice(i, i + BATCH_SIZE);
    const rows = batch.map(({ code, description }) =>
      `('${escape(code)}','${escape(description)}')`
    );
    lines.push(`INSERT INTO icd10_codes(code,description) VALUES`);
    lines.push(rows.join(',\n') + ';');
    lines.push('');
  }

  return lines.join('\n');
}

async function main() {
  await mkdir(TMP_DIR, { recursive: true });

  const zipPath = path.join(TMP_DIR, 'icd10.zip');
  try {
    await downloadZip(CMS_ZIP_URL, zipPath);
    const codesFile = await extractCodesFile(zipPath, TMP_DIR);

    console.log('Parsing codes ...');
    const codes = await parseCodes(codesFile);
    console.log(`Parsed ${codes.length} codes.`);

    const sql = buildSql(codes);
    await writeFile(OUT_FILE, sql, 'utf8');
    console.log(`Written to ${OUT_FILE}`);
    console.log(`Done. Re-run cargo test to verify icd10_seed_loads_minimum_codes.`);
  } finally {
    await rm(TMP_DIR, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
